### PR TITLE
The plugin should work both when running "sls offline" and "sls offline start"

### LINKED ISSUE #2: The plugin doesn't get initialized when running "sls offline start"
If it's supposed to just run when starting serverless offline `sls offline start`, then it doesn't seem to work. It doesn't log anything and  `kinesalite` is not started.

### PR DESCRIPTION
**Pull request by hakimio**
Fixes serverless offline hook and closes #2 .

### CODE REVIEW

**Comment by hakimio** [comment]
@yooouuri Can you merge this and release a new version? Thanks.

**Comment by yooouuri** [comment]
Let me test it and I will merge it.

**Comment by hakimio** [comment]
@yooouuri did you have any time to test it?

**Comment by YOU54F** [comment]
Hi @hakimio @yooouuri I have tested this and confirm it works. please could we merge and release. thank you 👍🏽

**Comment by hakimio** [comment]
@YOU54F I think the project is abandoned. You can use my `custom-build` branch to install the fix.
Put the following in your `package.json`:
```
"serverless-local-kinesis": "hakimio/serverless-local-kinesis#custom-build"
```
and run yarn/npm install.

**Pull request merged**
